// 'use client';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import { usePathname } from "next/navigation";
import { BaseStructure } from "./_components/BaseStructure";
import { ReactNode } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "School Project Nov 4",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  // const pathname = usePathname();
  // const isframePage = pathname.startsWith("/iframe");
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <BaseStructure>{children}</BaseStructure>
      </body>
    </html>
  );
}
//conditional basestructure rendering
